version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokedex_services_node
    ports:
      - "3333:3333"
    volumes:
      - .:/var/www
    command: sh -c "npm install && node ace serve --watch"
    networks:
      - pokedex
    expose:
      - 3333
    environment:
      - NODE_ENV=development
  nginx:
    image: nginx:latest
    container_name: pokedex_services_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - pokedex

  mariadb:
    image: mariadb
    container_name: pokedex_services_mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokedex
    networks:
      - pokedex

networks:
  pokedex:
